config/routes.rb
Awesome::Application.routes.draw do
  resources :aliens

  resources :pirates

end

app/models/alien.rb
class Alien < ActiveRecord::Base
  attr_accessible :name
end

app/models/pirate.rb
class Pirate < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController
  # GET /aliens
  # GET /aliens.json
  def index
    @aliens = Alien.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aliens }
    end
  end

  # GET /aliens/1
  # GET /aliens/1.json
  def show
    @alien = Alien.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alien }
    end
  end

  # GET /aliens/new
  # GET /aliens/new.json
  def new
    @alien = Alien.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alien }
    end
  end

  # GET /aliens/1/edit
  def edit
    @alien = Alien.find(params[:id])
  end

  # POST /aliens
  # POST /aliens.json
  def create
    @alien = Alien.new(params[:alien])

    respond_to do |format|
      if @alien.save
        format.html { redirect_to @alien, notice: 'Alien was successfully created.' }
        format.json { render json: @alien, status: :created, location: @alien }
      else
        format.html { render action: "new" }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aliens/1
  # PUT /aliens/1.json
  def update
    @alien = Alien.find(params[:id])

    respond_to do |format|
      if @alien.update_attributes(params[:alien])
        format.html { redirect_to @alien, notice: 'Alien was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliens/1
  # DELETE /aliens/1.json
  def destroy
    @alien = Alien.find(params[:id])
    @alien.destroy

    respond_to do |format|
      format.html { redirect_to aliens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pirates_controller.rb
class PiratesController < ApplicationController
  # GET /pirates
  # GET /pirates.json
  def index
    @pirates = Pirate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pirates }
    end
  end

  # GET /pirates/1
  # GET /pirates/1.json
  def show
    @pirate = Pirate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pirate }
    end
  end

  # GET /pirates/new
  # GET /pirates/new.json
  def new
    @pirate = Pirate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pirate }
    end
  end

  # GET /pirates/1/edit
  def edit
    @pirate = Pirate.find(params[:id])
  end

  # POST /pirates
  # POST /pirates.json
  def create
    @pirate = Pirate.new(params[:pirate])

    respond_to do |format|
      if @pirate.save
        format.html { redirect_to @pirate, notice: 'Pirate was successfully created.' }
        format.js
        format.json { render json: @pirate, status: :created, location: @pirate }
      else
        format.html { render action: "new" }
        format.json { render json: @pirate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pirates/1
  # PUT /pirates/1.json
  def update
    @pirate = Pirate.find(params[:id])

    respond_to do |format|
      if @pirate.update_attributes(params[:pirate])
        format.html { redirect_to @pirate, notice: 'Pirate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pirate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pirates/1
  # DELETE /pirates/1.json
  def destroy
    @pirate = Pirate.find(params[:id])
    @pirate.destroy

    respond_to do |format|
      format.html { redirect_to pirates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pirates_helper.rb
module PiratesHelper
end

app/views/aliens/_form.html.erb
<%= form_for(@alien) do |f| %>
  <% if @alien.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alien.errors.count, "error") %> prohibited this alien from being saved:</h2>

      <ul>
      <% @alien.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aliens/edit.html.erb
<h1>Editing alien</h1>

<%= render 'form' %>

<%= link_to 'Show', @alien %> |
<%= link_to 'Back', aliens_path %>

app/views/aliens/index.html.erb
<h1>Listing aliens</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aliens.each do |alien| %>
  <tr>
    <td><%= alien.name %></td>
    <td><%= link_to 'Show', alien %></td>
    <td><%= link_to 'Edit', edit_alien_path(alien) %></td>
    <td><%= link_to 'Destroy', alien, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alien', new_alien_path %>

app/views/aliens/new.html.erb
<h1>New alien</h1>

<%= render 'form' %>

<%= link_to 'Back', aliens_path %>

app/views/aliens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @alien.name %>
</p>


<%= link_to 'Edit', edit_alien_path(@alien) %> |
<%= link_to 'Back', aliens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pirates/_form.html.erb
<%= form_for(@pirate) do |f| %>
  <% if @pirate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pirate.errors.count, "error") %> prohibited this pirate from being saved:</h2>

      <ul>
      <% @pirate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pirates/create.js.erb
$('#pirates').prepend("<%=j render :partial => 'shared/pirate', :locals => {:p => @pirate} %>");

app/views/pirates/edit.html.erb
<h1>Editing pirate</h1>

<%= render 'form' %>

<%= link_to 'Show', @pirate %> |
<%= link_to 'Back', pirates_path %>

app/views/pirates/index.html.erb
<%= form_tag '/pirates', :remote => true do %>
 Name: 
 <%= text_field_tag 'pirate[name]' %> <br>
 <%= submit_tag 'Create a new Pirate!' %>
<% end %>

<div id="pirates">
  <%= render :partial => 'shared/pirate', :collection => @pirates, :as => :p %>
</div>

app/views/pirates/new.html.erb
<h1>New pirate</h1>

<%= render 'form' %>

<%= link_to 'Back', pirates_path %>

app/views/pirates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pirate.name %>
</p>


<%= link_to 'Edit', edit_pirate_path(@pirate) %> |
<%= link_to 'Back', pirates_path %>

app/views/shared/_pirate.html.erb
<div class="pirate">
  <b><%= p.name %></b>
</div>